name: Flutter CI/CD with Firebase App Distribution

on:
  pull_request:
    branches:
      - dev  # ✅ Runs only when a PR is made to dev

jobs:
  build:
    name: Build & Deploy Flutter App (PR to dev)
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK
      - name: Build release APK
        run: flutter build apk --release

      # Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Set up Firebase authentication (Reusing the same service account)
      - name: Set up Firebase authentication
        run: |
          printf '%s' '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > ${{ github.workspace }}/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV

      # Upload APK to Firebase App Distribution (Only on PR to dev)
      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ github.workspace }}/firebase-key.json
          groups: tech-club-leads
          file: build/app/outputs/flutter-apk/app-release.apk
